### ISSUE TITLE
Call to a member function getQuoted() on array

### ISSUE THREAD

**Issue by Mancy** [asipto/siremis-php#9] opened 2016-08-06 23:25 UTC
PHP Fatal error:  Call to a member function getQuoted() on array in /var/www/siremis-4.2.0/openbiz/bin/data/BizDataSql.php on line 237, referer: http://yourdomain.com/siremis/system/user_detail/1

**Comment by miconda** [comment] 2016-12-13 12:57
Fixed in latest master.

**Closed as completed by miconda** 2016-12-13 12:57 UTC

**Comment by imcdona** [comment] 2017-05-12 20:15
The download available at http://siremis.asipto.com/pub/downloads/siremis/siremis-4.3.0.tgz still has the old code and needs to be updated.

I can confirm that the issue is resolved after using the latest master from github.
